jwt:
  key:
    access: ZWNpLXNnLWp3dC1zZWNyZXQtc2ho
    refresh: ZWNpLXNnLWp3dC1zZWNyZXQtc2hoLXJlZnJlc2hlZA
  max-age:
    access: 5000000 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7

default :
  image :
    address : "src/main/prodmedia/image/default/default.PNG"
