server:
  port: 8180

upload:
  image:
    location: src/main/prodmedia/image/

spring:

  session:
    storage-type: redis

  redis:
    host: localhost
    password: qpqpqp0614
    port: 6379

  main:
    allow-bean-definition-overriding: true

  profiles:
    include: secret

  # database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thn
    platform: postgres
    username: postgres
    password: qpqpqp0614

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: create
      # update # When you launch the application for the first time
      # switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  # file upload
  servlet.multipart.max-file-size: 1500MB
  servlet.multipart.max-request-size: 1500MB

  # spring boot utf8
  http.encoding.charset: UTF-8
  http.encoding.enabled: true
  http.encoding.force: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher